name: OS
description: File a bug report
title: "Feature: "
labels: ["bug", "triage"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: What is your name?
      placeholder: ex. Sertha Taweewattana
      description: Thanks the taking the time to fill out this bug report!
    validations:
      required: false
  - type: dropdown
    id: request type
    attributes:
      label: Type of request?
      description: Select the tpye of your request
      placeholder: New Feature
      option: 
          - Window
          - macOS
          - Linux
          - Android
          - ios
    validations:
      required: true
- type: dropdown
    id: request type
    attributes:
      label: What is the OS which you want to suggest?
      placeholder: Selections :
      option: 
          - Window
          - macOS
          - Linux
          - Android
          - ios
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: What are the details of your suggestion?
      description: Explain what do you want
  
